name: Checks

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  qml:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Validate QML and JavaScript files
        uses: liri-infra/qmllint-action@8bfbc8ec90b2f48147db9b47403448eda7b20a31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
